version: '3'
services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "80:80"         # Graphite Web UI
      - "2003:2003"     # Carbon line receiver
      - "8125:8125/udp" # StatsD UDP
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"     # Grafana UI
    restart: always
